### ISSUE TITLE
changes to figure 4

### ISSUE THREAD

**Issue by rjsmethurst** [willettk/gzhubble#123]
I'd prefer to see the normalised histograms as opposed to a count - could we investigate what that looked like?  

I'm also in favour of changing the lines to dashed/dotdash/long dash etc. along with changing the legend so that it's not the default matplotlib weird box histogram. Can we add our own hacked legend with plt.axhline and plt.text?

**Comment by karenlmasters** [comment]
I like the counts - gives a visual sense of the different sizes of the samples. But I think normalized would be good too. I agree about the lines, but I'd put this as low priority to fix before submission.

**Comment by vrooje** [comment]
I agree that the counts provides good information too, though I also agree the simulated AGN are hard to spot. Could multiply that histogram by 10 and note that in the legend so you can see the details of it more clearly but don't lose the overall proportional information?

I think the lines should be adjusted as well just in case the referee is color blind.

**Comment by willettk** [comment]
Good points. I'd prefer to keep the actual counts vs. normalized; it'll look exactly the same, just with a different scale on the y-axis? Adding linestyles + a better histogram is a good idea, though. 

Assigning to @rjsmethurst, since she has a good eye for this. Data file is here: 

https://www.dropbox.com/s/l3803pfkrz66368/gz_hst_table.fits?dl=1

and the code to make the plot is in [classification_hist.py](https://github.com/willettk/gzhubble/blob/master/python/classification_hist.py).

**Comment by rjsmethurst** [comment]
@willettk Changes pushed to python file and figure - haven't pdflatex the tex file though so the pdf is not updated (just in case you'd made more changes to the tex file since)

**Comment by willettk** [comment]
Excellent! My doctrine of _"thou shalt not submit the PDF"_ is totally working.

**Comment by willettk** [comment]
Closed with #141.
