### ISSUE TITLE
comments on figure 6 

### ISSUE THREAD

**Issue by rjsmethurst** [willettk/gzhubble#124]
So in the text you mention that this exponential fitting is only done to galaxies with f_{features, z=0.3} > 0 - so what the hell is happening in the top right panel - it looks as if everything has been divided by almost zero or is it just the error bars are so huge it distracts? Could you comment on that panel in the caption because I think it's going to throw people off.

**Comment by karenlmasters** [comment]
Agreed that top panel (think you mean Fig 7) is confusing. If this is a random selection, could we just not show that one as an example? Or do we want to illustrate that this method doesn't work for all galaxies?

**Comment by willettk** [comment]
@bamford made this version with many more galaxies (807dbfb4e7dc6192d373cfc079a6d90da3a9a741); I think the effect is clearer since it sorts by `p_frac` and `evol`. What do you think of replacing the version of Figure 7 with this (or maybe a slightly smaller version)?

![download](https://cloud.githubusercontent.com/assets/2285931/15381802/811e480c-1d48-11e6-9876-8f14dbc29833.png)

**Comment by rjsmethurst** [comment]
I think the number you have in the original figure is better - but sorting by p_frac and evol does make it clearer. Still doesn't explain what was going on in the top panel of the original figure though...

**Comment by willettk** [comment]
I think @rjsmethurst is exactly right; it's trying to divide by zero and getting a crazy value for ζ as a result. You can see that f_features at z=0.3 was only 0.03 in the first place (a single vote), and everything afterwards was zero. We do exclude fits like this in evaluating our final calibration, limiting ζ to between -10 and 10. Ultimately, it doesn't affect our calibration - this is a very clean elliptical galaxy and computing a calibration at higher redshift doesn't change its f_features meaningfully.

I'd wondered about whether it'd be fair to exclude galaxies like this (which do, rarely, exist) - if I do, then it means it's not really a "randomly"-selected sample. On the other hand, galaxies like those aren't used in the fit and we could state explicitly in the caption why we're displaying the ones that we do. 

What about sorting by p_frac and evol, but with fewer numbers overall (say 6x6) so we don't obliterate the page and the reader. @bamford, could you make a version that sorts that?

**Comment by vrooje** [comment]
I really like that plot; I agree that the sorting by `f_features` and `evo` (though we perhaps could use a better term for the latter) is much, much clearer. 

We could probably do with this plot having ~10 original galaxies spread evenly among `f_features`, without worrying about surface brightness, unless there are cases where the `\mu` value really makes a huge difference (it doesn't look like it's a huge effect in the figure above). 

An alternative -- which I only suggest because this is for ApJS so should be pretty complete -- is to have 3 such plots, with 10 galaxies each spanning the range of f_features, but each plot showing galaxies from a different surface brightness level.

Also, as there are a lot of figure labels here I suggest an overall label for the right-y axis that is `high ---------> f_features -------> low` from top to bottom (or similar).

**Comment by bamford** [comment]
3) I think the suggested plot would work nicely. I will make it tomorrow.

2) "Randomly selected examples" is always "I kept randomly selecting until I got a nice set"

1) Dividing by nearly zero probably has something to do with it, but note that as zeta goes to high values the function simply becomes a horizontal line, so not badly behaved.

**Comment by bamford** [comment]
This is what I've got so far.  Basically the same plot, but with a few more panels, galaxies chosen to span the range of f_features,z=0.03 and ordered by f_features,z=0.03.
[zeta_examples.pdf](https://github.com/willettk/gzhubble/files/275059/zeta_examples.pdf)

**Comment by willettk** [comment]
Love it. Thank you, Steven!

**Comment by willettk** [comment]
Closed with 943b134fc6c36d4bc871ab061e0d76fa4ce8be70.

**Comment by willettk** [comment]
Hi Steven,

This figure you made for the last submitted draft was deemed universally
great. We had a couple tweaks we wanted to make to it based on the slightly
different normalization we now have. If you still have the code used to
make this plot, could you send it to me or post in the repo? Mel and I can
make the final version, but it'd be much easier if we could go off your
existing code.
- many thanks,
  Kyle

**Comment by bamford** [comment]
@kyle and @Mel23, the code is [here](https://github.com/bamford/gzhubble/blob/zeta_examples/python/fzeta_examples.py).

**Comment by willettk** [comment]
Brilliant. Thanks, @bamford.
