### ISSUE TITLE
Figure 12  comparison with existing morphology

### ISSUE THREAD

**Issue by claudiascarlata** [willettk/gzhubble#133]
There are various things that are unclear in this section of the paper -- and that are worrying. (keep in mind that one of those people will be the referee of your paper).
- [x] do you use all GZH classifications? or only the debiassed ones?
- [x] do you use all redshifts? And magnitudes? We certainly say we believe our classifications at most to z=1. Also for ZEST: did you make the change I suggested?
- [x] In Figure 12 you report the numbers of ellipticals/spirals/irregular. But that number should be different for Cassata/tasca/scarlata/Bundy and so on. Why do we have only two boxes with those numbers? I would have expected one per dataset/classifier.
- [x] Redo the matched catalogs with the same positional radius (0.5 arcsec)

**Comment by willettk** [comment]
See parallel discussion in #78.

**Comment by willettk** [comment]
Also: redo all matches with the same radius of 0.5".

**Comment by willettk** [comment]
I'll put a version of this into the main draft, but I've redone the comparisons now with volume-limited samples instead of throwing everything in there (which should be much fairer). 

Here are the original comparisons with no cuts of any kind:

![comparisons](https://cloud.githubusercontent.com/assets/2285931/15520952/95d60796-21ce-11e6-97f7-a4e34a9f3096.png)

Here are the comparisons using only volume-limited samples to our formal limits (z < 1.0; m < 22.5 in GEMS and m < 23.5 in all other surveys):

![comparisons_vl](https://cloud.githubusercontent.com/assets/2285931/15520989/cc1d099e-21ce-11e6-8764-39901fce15bd.png)

And here's what I think should be the version we analyze, down to 22.5 in all three surveys (@claudiascarlata suggested this for COSMOS specifically, and it's probably the practical limit for getting information from all the HST surveys):

![comparisons_vl_22 5](https://cloud.githubusercontent.com/assets/2285931/15549014/4e07ad64-2270-11e6-82d7-7796a018c9cf.png)

I'm super encouraged by this. There's actually a correlation now in all the automatic measurements!!
