### ISSUE TITLE
Section 4

### ISSUE THREAD

**Issue by bamford** [willettk/gzhubble#140]
- [x] SB confusion mentioned in #135; we need to be clearer what measure of SB we are talking about, and are we using the same measurement of SB for simulated and real galaxies?
- [x] 4.1: "is a function of the apparent size and brightness of the image as seen on screen" --> "is a function of the apparent size and brightness of the galaxy"
- [x] 4.1: "and the exponential function bounds the observed vote fractions between f_{mu,z}=0.3 and zero." What does this mean?
- [x] 4.1: "delta chi^2 > 3.0" needs more explanation; delta with respect to what?
- [x] Equation (2) shouldn't use zeta for the coefficients (zeta_0 and zeta_1) as it is confusing (linear versus log).  Perhaps just a and b?  Also, the provided coefficients (0.1, 1.4) don't match the plot.
- [x] The change from Eqn. (1) to Eqn. (3) isn't sufficiently explained.  I'm quite concerned it isn't valid to fit zeta with one equation and then just use the same parameter value in a different equation.  
- [x] Rather than the convex hull methodology, wouldn't it not have been pretty much equivalent to just say galaxies with f_features < 0.3 cannot be debiased?
- [x] 'NEI' needs to be more clearly defined (or just use words) in Table 4.
- [x] How can you plot NEI objects in Fig. 11?
- [x] Given how uniform zeta is, couldn't you just assume the average for all the NEI objects?
- [x] There isn't really any evidence for a dependence of zeta on SB, certainly not in the current figures (even though there is a increase in zeta for simulations with strong luminosity evolution), so it may be best to not bother with it.
- [x] Fig. 7 (in progress in #124): "Error bars are Poissonian" – actually they are Binomial for each f, symmetrised, then added in quadrature, probably best to just not explain them!

**Comment by bamford** [comment]
Sorry the above points are a bit jumbled.  I'm digging through the code trying to work out how the debiasing is applied.  Maybe we should talk over some of the bigger issues via Skype or Slack next week.

**Comment by willettk** [comment]
Thanks for the careful reads. I'll work hard on this over the weekend; earlier will be much preferred, since we're madly dashing to see if it can be submitted by next Friday. Please do keep posting stuff here!

**Comment by Mel23** [comment]
> > SB confusion mentioned in #135; we need to be clearer what measure of SB we are talking about, and are we using the same measurement of SB for simulated and real galaxies?

The paper does state that the surface brightness measurements of the simulated galaxies was measured by SExtractor (again, a point which referencing Tom's thesis would be useful), and that the surface brightnesses for the real galaxies were from the AGS-GC catalog. While both were measured using I-band apparent mags, it's fair to say they aren't 100% apples-to-apples SBs. 

I did catch some places where mu_r was used instead of mu_i - mu_r was used to evenly select FERENGI galaxies spanning a range of SBs, mu_i was used in the debiasing process to compare as close to Hubble as possible. 

> > 4.1: "is a function of the apparent size and brightness of the image as seen on screen" --> "is a function of the apparent size and brightness of the galaxy"

I agree here, the former almost implies we're measuring the bias induced by brightness of a computer screen, rather than the galaxy/image. 

> > 4.1: "and the exponential function bounds the observed vote fractions between f_{mu,z}=0.3 and zero." What does this mean?

We are assuming that for a perfect model, the observed vote fraction at high redshift will always be lower than that observed at z = 0.3, and that the vote fraction cannot be less than zero. I've added a sentence to clear that up in the text. 

> > "delta chi^2 > 3.0" needs more explanation; delta with respect to what?

might need Kyle to comment on this one 

> > Equation (2) shouldn't use zeta for the coefficients (zeta_0 and zeta_1) as it is confusing (linear versus log).  Perhaps just a and b?  Also, the provided coefficients (0.1, 1.4) don't match the plot.

Thanks for the catch! Changed to the correct coefficients. 

> > The change from Eqn. (1) to Eqn. (3) isn't sufficiently explained.  I'm quite concerned it isn't valid to fit zeta with one equation and then just use the same parameter value in a different equation. 

 This is worth discussing - I'll come back to this

> > Rather than the convex hull methodology, wouldn't it not have been pretty much equivalent to just say galaxies with f_features < 0.3 cannot be debiased?

In hindsight, yes that is mostly true; but it's not exactly quanitatively motivated. We can go slightly lower in f_features(z=0.3) at low redshift, so it is worth it (I think) to keep the method to maximize the number of galaxies we can accurately debias. By setting a ~by-eye cut of f<0.3 for all galaxies regardless of redshift, we'd gain some clarity/simplicity of the process, but at the expense of not correcting galaxies which could be corrected. 

> > 'NEI' needs to be more clearly defined (or just use words) in Table 4.

Added explanation of NEI in 4.2

> > How can you plot NEI objects in Fig. 11?
> > 
> > Given how uniform zeta is, couldn't you just assume the average for all the NEI objects?

Honestly? We probably could. We didn't know going into this how weak of a dependence surface brightness would be going into this. The main problem is that without corresponding FERENGI data, we don't know how low we can go in f_features and still be correctable, unless we change everything and remove _any_ SB dependence from the process. At some point a decision has to be made about making the perfect paper vs. ever publishing it, and redoing that would take some work.

That said... ~10,000 NEI galaxies are between 0.3<z<1.0 and have f_features >0.3. We do have the debiased values in the catalog, so if an argument can be made that they are trustworthy, it might be worth using these as the 'best' values instead of the weighted values. I'll discuss more with Kyle on this. 

> > There isn't really any evidence for a dependence of zeta on SB, certainly not in the current figures (even though there is a increase in zeta for simulations with strong luminosity evolution), so it may be best to not bother with it.

see comment above.

**Comment by bamford** [comment]
Sorry I'm being so slow to contribute. I'll continue to work through and chime in over the next few days. Seems like it is rapidly coming together though, so hope you make your Friday target @willettk.

Thanks for all the detail response @Mel23!

What I mean about being careful about the surface brightness, is that it could be central SB (max?), empirical or model based; SB within the half-light radius; SB at the half-light radius, etc. I'm concerned the offsets might just be due to them being different SB measurements. I'm surprised the real galaxies are FAINTER than the simulations, because I thought that we needed luminosity evolution to be able to see anything at all in the high-z FERENGI images.  @karenlmasters's comment in #135  suggests the opposite, that the real galaxies are higher SB than the simulations, which matches my expectations. So it feels like something is awry with this plot, and hence potentially with all the SB matching for the debiasing.

**Comment by Mel23** [comment]
Thank you for clearing that up! And yes this is an extremely important point - we brought this up today in discussion at MN and are exploring this issue in depth; will report with results asap.
