### ISSUE TITLE
Merge with other repository?

### ISSUE THREAD

**Issue by karenlmasters** [willettk/gzhubble#4]
I'm not so great at github (yet). How would we merge this/link this to the other repository from the work Kevin and I did in Taiwan?

**Comment by willettk** [comment]
It's not hard to merge the content. Do we want everything from the Taiwan
repo? Alternatively, we could just move it over there and make it our
working group.

The main thing I don't like about the Taiwan repo is that it's private;
hard to remember who has access sometimes.

**Comment by karenlmasters** [comment]
I think we should grab all of it.

**Comment by willettk** [comment]
Added content with 46ed4c2ce6efb82962cd52f85822c144e884996c. We should be careful in the future not to add too many big datasets if possible (lots of image files or metadata, for example). Since Github remembers EVERYTHING that's ever committed, changing them tends to bloat the total size of the repository.
