### ISSUE TITLE
Rewrite section 4.1

### ISSUE THREAD

**Issue by chrislintott** [willettk/gzhubble#70]
Section 4.1 and table 2 are very confusing. 

In particular: 

'For each of the four target redshifts...the images were redshifted in delta z=0.1 bins up to z_sim=1'

I think this means that there were four target redshifts and for each galaxy we then shifted to 0.1, 0.2, 0.3 etc. It is therefore mystifying that there are more images (and higher N_zbins in the table) for the more distant target redshifts.

The choice of e_max is not discussed either.

**Comment by Mel23** [comment]
I'm in favor of revising this section for those reasons... The 'target'
FERENGI redshifts are basically the lowest redshift attainable for the
image. Since we only use data from those galaxies with z_target = 0.3, I'm
not convinced it's worth mentioning the other data exists. Going into
detail of the original sample selection methods for FERENGI is technically
more complete, but I think we sacrifice clarity by including it.

**Comment by willettk** [comment]
Closed with #145.
