### ISSUE TITLE
Treatment of anon users

### ISSUE THREAD

**Issue by chrislintott** [willettk/gzhubble#81]
Does it make sense to lump all of these classifications together and give the average anonymous user a weight? My guess is they would appear in the middle of the pack, so this wouldn't matter too much but it'd be good to know what the weight would be. (It would be interesting if anonymous users are worse...)

**Comment by vrooje** [comment]
You'd probably want to make sure you removed the obvious bots first...

But we effectively did this by accident during Pulsar Hunters. A bug in the way IP addresses were being reported meant it looked like we had <5 anonymous users, each of which had done classifications at super-human speed and had really very high weightings. The weightings were on par with an experienced user, if I recall correctly.

**Comment by bamford** [comment]
Remember the weights for 95% of users are = 1.  Only the poorest 5% are down-weighted.  So the anon users would have a weight of 1.  Maybe best to say "they receive the same unit weighting as the vast majority of logged-in classifiers", rather than "no weighting is applied".

**Comment by willettk** [comment]
I'll comment that I don't know how many anonymous GZ users there were; the SQL database I have lists 93,898 `zooniverse_users` with a `zooniverse_user_id`, but the corresponding `users` table (which has their login name, confirming that they exist) has only 2,735 entries, which is way too few. And every classification has a `zooniverse_user_id` that matches to the first table; but I don't know what percentage of them are anonymous. 

It'd be useful (not required), but I'm not sure I have the most updated data. If anyone has the SQL tables to answer, that, please shout (and consider putting them on a more centrally available archive).

**Comment by bamford** [comment]
The database dump I used for the final GZ:HST data tables is:
https://s3.amazonaws.com/zooniverse-code/databases/011112/hubble_011112.sql.gz
although I no longer have access to the Zooniverse AWS account and the public link has expired (cc @chrislintott). Someone with Zooniverse AWS keys should be able to get the file.  It would be good to put it somewhere obvious.  Copies of the raw GZ1 and GZ2 databases are on my S3 - I don't know if they got put somewhere more official, so I'd be happy to store the GZ:HST ones alongside

FWIW, I tried looking into the anonymous user numbers by spinning up an AWS instance using an EC2 volume I used for the last GZ:HST reduction, but it was taking longer than anticipated due to depreciated Ubuntu versions, MySQL versions, etc., so I gave up.  I can get the GZ:HST database up and running if needed, but probably not until next week now as I have imminent exam marking.

**Comment by willettk** [comment]
That's extremely useful, Steven - Chris and I talked more this week about
creating a consistent archive of all the various GZ data that's accessible
to everyone. The raw classifications from GZ, GZ2, and GZH should all be a
key part of that.

I looked in the directory you mentioned to check if it matches mine; 011112
doesn't currently exist on the zooniverse-code bucket. There is 011012,
which has a file hubble_011012.sql.gz (654.8 MB). However, I can't download
it, despite having permissions for the bucket, which is odd.

I can ask Adam to help me download that file and we can check against your
latest version.

**Comment by vrooje** [comment]
If the file hasn't been accessed in a while it will have been archived to
glacier and will need retrieving before it can be downloaded. You might be
able to do it from the web interface... Or possibly @astopy has to; not
sure.

**Comment by adammcmaster** [comment]
Let me know if you still need that database dump. It contains user email addresses, passwords, etc. so I'll need to clean it up first.

**Comment by bamford** [comment]
Yes, we still need it to go somewhere with the GZ1 & 2 databases for posterity.  They also contain user info, so are not for distribution.  If you do decide to remove sensitive information, please ensure user ids are definitely not affected, so we can make use the full history of the classifications (e.g. for training ML algorithms, studying behaviour, etc. in future).  However, that is something we should also do with the GZ1 & 2 databases for consistency (may already have been done, but I don't know the location of such 'sanitised' versions).
