### ISSUE TITLE
Distraction bias?

### ISSUE THREAD

**Issue by chrislintott** [willettk/gzhubble#82]
Is distraction bias relevant when the galaxy is centered? I'm not at all convinced, and would remove this reference.

**Comment by karenlmasters** [comment]
I would say it is relevant... but I've probably read less about it than Chris.

**Comment by willettk** [comment]
I'm conjecturing that there's an effect, but Chris is right that we've never quantified what it would be for images in Galaxy Zoo. The Andromeda Project reference is a more specific case. There's a good research project in that for a student, I'd imagine.

**Comment by vrooje** [comment]
I noted it in the GZC paper -- there are cases where the central galaxy is a faint, fuzzy blob and there's a whopping spiral nearby, which significantly skews the vote fractions even after weighting.

**Comment by vrooje** [comment]
(Note, I didn't cite Johnson et al. 2015 when discussing distraction bias because I thought I remembered that @lcjohnso didn't end up discussing it in that paper.)

**Comment by vrooje** [comment]
Example: this subject has a weighted f_spiral = 0.93, out of 32 votes (31.4 weighted votes):

![UDS_7657](http://www.galaxyzoo.org.s3.amazonaws.com/subjects/standard/UDS_7657.jpg)

These examples are rare but clear.

**Comment by willettk** [comment]
So strike Johnson et al. and cite Simmons et al. instead?

**Comment by vrooje** [comment]
I'll confirm that with Cliff when he's back in the office.

**Comment by karenlmasters** [comment]
Is that more "didn't classify the central galaxy bias" than "distraction bias"?

**Comment by vrooje** [comment]
I suspect we're dealing with a fuzzy definition here. I think of "distraction bias" as being from a category of distractions that cause misclassification, either by causing the classifier to miss something or by causing the classifier to classify the wrong thing. A direct comparison with AP is hard because that's discovery-based; but I saw 2 different kinds in the GZC paper. The first was the "classified a different galaxy in the image" bias, and the second was obvious in some of the classifications of the CANDELS team, where all classifiers missed an obvious bar or spiral or other feature, presumably because there were too many options to choose from. So this is a bit different but I still think of it as distraction bias...

**Comment by vrooje** [comment]
Spoke to Cliff; he confirmed that they ended up punting discussion of distraction bias in the AP release paper because it turned out to be much more complicated than they'd initially thought. That is, it seemed as though the addition of simulated clusters increased the stochasticity in detection of real clusters, such that some were dramatically underclassified _and_ others were dramatically overclassified compared to their cluster marking scores without a simulated cluster nearby. And the outliers weren't all that common, so the average correction seemed to be 0. However, they didn't feel they really had enough (or quite the right) data to state with confidence that this was the case. So they just left it for a future work.

**Comment by willettk** [comment]
Very good to know (and a sign that I didn't read the AP paper closely enough). Will remove the reference.

**Comment by willettk** [comment]
Closed with #122.
